---
apiVersion: v1
kind: Service
metadata:
  name: stocksvc
  labels:
    app: stocksvc
spec:
  ports:
    - port: 8000
      name: stocksvc-http
      targetPort: 8000
      protocol: TCP
  selector:
    app: stocksvc